/*
Team API


The team API lets you manage users, departments, locations, and cards.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  CardsApi,
  CompaniesApi,
  DepartmentsApi,
  LocationsApi,
  TitlesApi,
  UsersApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { BrexTeamCustom } from "./client-custom";

export class BrexTeam extends BrexTeamCustom {
  readonly cards: CardsApi;
  readonly companies: CompaniesApi;
  readonly departments: DepartmentsApi;
  readonly locations: LocationsApi;
  readonly titles: TitlesApi;
  readonly users: UsersApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.cards = new CardsApi(configuration);
    this.companies = new CompaniesApi(configuration);
    this.departments = new DepartmentsApi(configuration);
    this.locations = new LocationsApi(configuration);
    this.titles = new TitlesApi(configuration);
    this.users = new UsersApi(configuration);
  }

}
