/*
Team API


The team API lets you manage users, departments, locations, and cards.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ThreeDomainSecureEnabledPreference } from './three-domain-secure-enabled-preference';

/**
 * 
 * @export
 * @interface CardAttributePreferences
 */
export interface CardAttributePreferences {
    /**
     * 
     * @type {ThreeDomainSecureEnabledPreference}
     * @memberof CardAttributePreferences
     */
    'three_domain_secure_enabled_preference'?: ThreeDomainSecureEnabledPreference;
}

