/*
Team API


The team API lets you manage users, departments, locations, and cards.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';

/**
 * 
 * @export
 * @interface CardMailingAddress
 */
export interface CardMailingAddress {
    /**
     * Address line 1, no PO Box.
     * @type {string}
     * @memberof CardMailingAddress
     */
    'line1'?: string | null;
    /**
     * Address line 2 (e.g., apartment, suite, unit, or building).
     * @type {string}
     * @memberof CardMailingAddress
     */
    'line2'?: string | null;
    /**
     * City, district, suburb, town, or village.
     * @type {string}
     * @memberof CardMailingAddress
     */
    'city'?: string | null;
    /**
     * For US-addressed the 2-letter State abbreviation. For international-addresses the county, providence, or region.
     * @type {string}
     * @memberof CardMailingAddress
     */
    'state'?: string | null;
    /**
     * Two-letter country code (ISO 3166-1 alpha-2).
     * @type {string}
     * @memberof CardMailingAddress
     */
    'country'?: string | null;
    /**
     * ZIP or postal code.
     * @type {string}
     * @memberof CardMailingAddress
     */
    'postal_code'?: string | null;
    /**
     * Phone number.
     * @type {string}
     * @memberof CardMailingAddress
     */
    'phone_number'?: string | null;
}

