/*
Team API


The team API lets you manage users, departments, locations, and cards.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CardExpiration } from './card-expiration';

/**
 *  Card number, CVV, and expiration date of a card. 
 * @export
 * @interface CardNumberResponse
 */
export interface CardNumberResponse {
    /**
     * 
     * @type {string}
     * @memberof CardNumberResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CardNumberResponse
     */
    'number': string;
    /**
     * 
     * @type {string}
     * @memberof CardNumberResponse
     */
    'cvv': string;
    /**
     * 
     * @type {CardExpiration}
     * @memberof CardNumberResponse
     */
    'expiration_date': CardExpiration;
}

