/*
Team API


The team API lets you manage users, departments, locations, and cards.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AccountType } from './account-type';
import { Address } from './address';

/**
 * 
 * @export
 * @interface CompanyResponse
 */
export interface CompanyResponse {
    /**
     * 
     * @type {string}
     * @memberof CompanyResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CompanyResponse
     */
    'legal_name': string;
    /**
     * 
     * @type {Address}
     * @memberof CompanyResponse
     */
    'mailing_address': Address;
    /**
     * 
     * @type {AccountType}
     * @memberof CompanyResponse
     */
    'accountType': AccountType;
}

