/*
Team API


The team API lets you manage users, departments, locations, and cards.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CreateUserRequest
 */
export interface CreateUserRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateUserRequest
     */
    'first_name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserRequest
     */
    'last_name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUserRequest
     */
    'manager_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUserRequest
     */
    'department_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUserRequest
     */
    'location_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUserRequest
     */
    'title_id'?: string | null;
    /**
     * The metadata or customized attributes of the user. Maximum number of entries: 100
     * @type {{ [key: string]: string; }}
     * @memberof CreateUserRequest
     */
    'metadata'?: { [key: string]: string; } | null;
}

