/*
Team API


The team API lets you manage users, departments, locations, and cards.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Money } from './money';
import { SpendControlRequest } from './spend-control-request';
import { SpendDuration } from './spend-duration';

/**
 * 
 * @export
 * @interface CreateCardRequestSpendControls
 */
export interface CreateCardRequestSpendControls {
    /**
     * 
     * @type {Money}
     * @memberof CreateCardRequestSpendControls
     */
    'spend_limit': Money;
    /**
     *      Spend limit refresh frequency     - MONTHLY: The spend limit refreshes every month     - QUARTERLY: The spend limit refreshes every quarter     - YEARLY: The spend limit refreshes every year     - ONE_TIME: The limit does not refresh 
     * @type {SpendDuration}
     * @memberof CreateCardRequestSpendControls
     */
    'spend_duration': SpendDuration;
    /**
     * 
     * @type {string}
     * @memberof CreateCardRequestSpendControls
     */
    'reason'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCardRequestSpendControls
     */
    'lock_after_date'?: string | null;
    /**
     *  If using the Empower platform, a new `budget` will be created for this card. You can specify a `parent_budget` that your new `budget` will be nested under. If `parent_budget_id` is null, we will nest the new budget under the top-level account `budget`. 
     * @type {string}
     * @memberof CreateCardRequestSpendControls
     */
    'parent_budget_id'?: string | null;
}

