/*
Team API


The team API lets you manage users, departments, locations, and cards.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CardMailingAddress } from './card-mailing-address';
import { CardOwner } from './card-owner';
import { CardType } from './card-type';
import { CreateCardRequestCardAttributePreferences } from './create-card-request-card-attribute-preferences';
import { CreateCardRequestSpendControls } from './create-card-request-spend-controls';
import { LimitType } from './limit-type';

/**
 *  The `spend_controls` field is required when `limit_type` = `CARD`. The `shipping_address` field is required for physical cards, and the first 2 lines of the address must be under 60 characters long. 
 * @export
 * @interface CreateCardRequest
 */
export interface CreateCardRequest {
    /**
     * 
     * @type {CardOwner}
     * @memberof CreateCardRequest
     */
    'owner': CardOwner;
    /**
     * 
     * @type {string}
     * @memberof CreateCardRequest
     */
    'card_name': string;
    /**
     * 
     * @type {CardType}
     * @memberof CreateCardRequest
     */
    'card_type': CardType;
    /**
     *  `limit_type = CARD` for vendor cards. Vendor cards must have a `card_type` of `VIRTUAL`  and do not rely on the user specific limit.   For corporate cards, `limit_type = USER`.  Learn more about different card types [here](https://support.brex.com/what-are-the-different-types-of-cards-i-can-get/). 
     * @type {LimitType}
     * @memberof CreateCardRequest
     */
    'limit_type': LimitType;
    /**
     * 
     * @type {CreateCardRequestSpendControls}
     * @memberof CreateCardRequest
     */
    'spend_controls'?: CreateCardRequestSpendControls;
    /**
     * 
     * @type {CardMailingAddress}
     * @memberof CreateCardRequest
     */
    'mailing_address'?: CardMailingAddress;
    /**
     *  Set of key value pairs associated with this object. Please do not store any personally identifiable or sensitive information here. Limitations: maximum of 50 keys, keys cannot exceed 40 characters, values cannot exceed 500 characters.  
     * @type {{ [key: string]: string; }}
     * @memberof CreateCardRequest
     */
    'metadata'?: { [key: string]: string; } | null;
    /**
     * 
     * @type {CreateCardRequestCardAttributePreferences}
     * @memberof CreateCardRequest
     */
    'card_attribute_preferences'?: CreateCardRequestCardAttributePreferences;
}

