/*
Team API


The team API lets you manage users, departments, locations, and cards.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DepartmentResponse
 */
export interface DepartmentResponse {
    /**
     * Description of the department
     * @type {string}
     * @memberof DepartmentResponse
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DepartmentResponse
     */
    'id': string;
    /**
     * Name of the department
     * @type {string}
     * @memberof DepartmentResponse
     */
    'name': string;
}

