/*
Team API


The team API lets you manage users, departments, locations, and cards.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 *  `limit_type = CARD` for vendor cards. Vendor cards must have a `card_type` of `VIRTUAL`  and do not rely on the user specific limit.   For corporate cards, `limit_type = USER`.  Learn more about different card types [here](https://support.brex.com/what-are-the-different-types-of-cards-i-can-get/). 
 * @export
 * @enum {string}
 */
export type LimitType = 'CARD' | 'USER'

