/*
Team API


The team API lets you manage users, departments, locations, and cards.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DepartmentResponse } from './department-response';

/**
 * 
 * @export
 * @interface PageDepartmentResponse
 */
export interface PageDepartmentResponse {
    /**
     * 
     * @type {string}
     * @memberof PageDepartmentResponse
     */
    'next_cursor'?: string | null;
    /**
     * 
     * @type {Array<DepartmentResponse>}
     * @memberof PageDepartmentResponse
     */
    'items': Array<DepartmentResponse>;
}

