/*
Team API


The team API lets you manage users, departments, locations, and cards.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Card } from './card';

/**
 * 
 * @export
 * @interface PageCard
 */
export interface PageCard {
    /**
     * 
     * @type {string}
     * @memberof PageCard
     */
    'next_cursor'?: string | null;
    /**
     * 
     * @type {Array<Card>}
     * @memberof PageCard
     */
    'items': Array<Card>;
}

