/*
Team API


The team API lets you manage users, departments, locations, and cards.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SecureEmailForCardDetailsRequest
 */
export interface SecureEmailForCardDetailsRequest {
    /**
     * Email address to send card details to
     * @type {string}
     * @memberof SecureEmailForCardDetailsRequest
     */
    'recipient_email'?: string;
    /**
     * Sender name. Shows up in the subject of the email
     * @type {string}
     * @memberof SecureEmailForCardDetailsRequest
     */
    'sender_name'?: string;
    /**
     * Message to send with the card details
     * @type {string}
     * @memberof SecureEmailForCardDetailsRequest
     */
    'message'?: string | null;
    /**
     * Link expiry in number of days. Defaults to 30
     * @type {number}
     * @memberof SecureEmailForCardDetailsRequest
     */
    'expiry_days'?: number | null;
}

