/*
Team API


The team API lets you manage users, departments, locations, and cards.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SetUserLimitRequestMonthlyLimit } from './set-user-limit-request-monthly-limit';

/**
 * Request that sets the monthly user limit.
 * @export
 * @interface SetUserLimitRequest
 */
export interface SetUserLimitRequest {
    /**
     * 
     * @type {SetUserLimitRequestMonthlyLimit}
     * @memberof SetUserLimitRequest
     */
    'monthly_limit'?: SetUserLimitRequestMonthlyLimit;
}

