/*
Team API


The team API lets you manage users, departments, locations, and cards.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 *      Spend limit refresh frequency     - MONTHLY: The spend limit refreshes every month     - QUARTERLY: The spend limit refreshes every quarter     - YEARLY: The spend limit refreshes every year     - ONE_TIME: The limit does not refresh 
 * @export
 * @enum {string}
 */
export type SpendDuration = 'MONTHLY' | 'QUARTERLY' | 'YEARLY' | 'ONE_TIME'

