/*
Team API


The team API lets you manage users, departments, locations, and cards.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 *  Whether to enable 3-D secure protocol on this card.  
 * @export
 * @enum {string}
 */
export type ThreeDomainSecureEnabledPreference = 'THREE_DOMAIN_SECURE_ENABLED' | 'THREE_DOMAIN_SECURE_DISABLED'

