/*
Team API


The team API lets you manage users, departments, locations, and cards.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TitleResponse
 */
export interface TitleResponse {
    /**
     * 
     * @type {string}
     * @memberof TitleResponse
     */
    'id': string;
    /**
     * Name of the title
     * @type {string}
     * @memberof TitleResponse
     */
    'name': string;
}

