/*
Team API


The team API lets you manage users, departments, locations, and cards.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { UpdateCardRequestSpendControls } from './update-card-request-spend-controls';

/**
 * 
 * @export
 * @interface UpdateCardRequest
 */
export interface UpdateCardRequest {
    /**
     * 
     * @type {UpdateCardRequestSpendControls}
     * @memberof UpdateCardRequest
     */
    'spend_controls'?: UpdateCardRequestSpendControls;
    /**
     *  Set of key value pairs associated with this object. Please do not store any personally identifiable or sensitive information here. Limitations: maximum of 50 keys, keys cannot exceed 40 characters, values cannot exceed 500 characters.  
     * @type {{ [key: string]: string; }}
     * @memberof UpdateCardRequest
     */
    'metadata'?: { [key: string]: string; } | null;
}

