/*
Team API


The team API lets you manage users, departments, locations, and cards.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 *  Acceptable user status for update. To suspend a user, set status to \'disabled\'. To unsuspend a user, set status to \'active\'. 
 * @export
 * @enum {string}
 */
export type UpdateUserStatus = 'ACTIVE' | 'DISABLED'

